plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    compileSdk = compile_sdk_version
    namespace = 'io.legado.app.theme'
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    defaultConfig {
        minSdk 21
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.androidx.annotation
}
